import type { NextPage } from "next";
import Head from "next/head";
import Grid from "../components/Grid";
import styles from "../styles/Home.module.css";
import RARITIES_DATA from "../data/rarities.json";
import BlergPreview from "../components/BlergPreview";
import Link from "next/link";
import { styled } from "../theme/stitches.config";
import Tabs from "../components/Tabs";
import { BlergRarity } from "../types";
import { useWallet } from "@web3-ui/core";

const Home: NextPage = () => {
  const { connected } = useWallet();

  return (
    <div className={styles.container}>
      <Head>
        <title>Blergs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Tabs
        showTabs={connected}
        defaultTabId="allBlergs"
        title="Filter Blergs"
        tabs={[
          {
            content: <BlergsGrid blergs={RARITIES_DATA.slice(0, 5)} />,
            id: "allBlergs",
            title: "All",
          },
          {
            content: <BlergsGrid blergs={RARITIES_DATA.slice(0, 2)} />,
            id: "myBlergs",
            title: "Mine",
          },
        ]}
      />
    </div>
  );
};

export default Home;

const BlergLink = styled("a", {
  overflow: "hidden",
  aspectRatio: "1/1",
});

interface BlergsGridProps {
  blergs: BlergRarity[];
}

const BlergsGrid = ({ blergs }: BlergsGridProps) => {
  return (
    <main className={styles.main}>
      <Grid>
        {blergs.map((blerg) => (
          <Link key={blerg.tokenId} href={`/blerg/${blerg.tokenId}`} passHref>
            <BlergLink>
              <BlergPreview blerg={blerg} />
            </BlergLink>
          </Link>
        ))}
      </Grid>
    </main>
  );
};
