import type { NextPage } from "next";
import Head from "next/head";
import Grid from "../components/Grid";
import styles from "../styles/Home.module.css";
import RARITIES_DATA from "../data/rarities.json";
import BlergPreview from "../components/BlergPreview";
import Link from "next/link";
import { styled } from "../theme/stitches.config";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blergs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <Grid>
          {RARITIES_DATA.map((blerg) => (
            <Link key={blerg.tokenId} href={`/blerg/${blerg.tokenId}`} passHref>
              <BlergLink>
                <BlergPreview blerg={blerg} />
              </BlergLink>
            </Link>
          ))}
        </Grid>
      </main>
    </div>
  );
};

export default Home;

const BlergLink = styled("a", {
  overflow: "hidden",
  aspectRatio: "1/1",
});
